#include "timey_pch.h"
#include "DataBase.h"
#include "tuple"

namespace Timey {

	using test = TableStmt<"projects", PrimaryKeys<ColumnStmt<"project_id", ColumnType::Integer, NotNullCol>>, void, 
		ColumnStmt<"project_id", ColumnType::Integer, NotNullCol>,
		ColumnStmt<"color_r", ColumnType::Real, NotNullCol, ColConstraint<"CHECK (0 <= color_r AND 1 >= color_r)">>,
		ColumnStmt<"color_g", ColumnType::Real, NotNullCol, ColConstraint<"CHECK (0 <= color_g AND 1 >= color_g)">>,
		ColumnStmt<"color_b", ColumnType::Real, NotNullCol, ColConstraint<"CHECK (0 <= color_b AND 1 >= color_b)">>
	>;

	static constexpr meta::string result = test::stmt;
	 

	void print_res() {
		
		TIMEY_CORE_INFO((char const*)result);
	}
	//TODO :1. Make PrimaryKeys a column constraint rather then a table constraint.
	//		2. Make the Check expr column constraint.
	//		3. Establish a more formal testing for the autogenerated qureies. 
}